=== jwilk-mirrors/zvbi/test/cc608-test-stream.dtd
<!--
  Libzvbi EIA 608-B Closed Caption Test Stream DTD 2.0

  Copyright (C) 2006, 2008 Michael H. Schimek

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License version 2 as
  published by the Free Software Foundation.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
  MA 02110-1301, USA.

  $Id: cc608-test-stream.dtd,v 1.1 2009-12-14 23:43:43 mschimek Exp $

  This is the format of the string loaded with
  vbi_capture_sim_load_caption(). Note the XML parser is very
  simple and does not support most XML features.

  All printable characters (e.g. spaces but not tabs or line feeds) are
  directly inserted into the stream, with an odd parity bit. Note the
  basic caption character set is based on but not identical to ASCII. A
  zero (0x80) padding byte may be inserted between an odd number of
  characters and a control code. To transmit a left or right angle
  bracket or ampersand enter the &lt; &gt; or &amp; entity. &#number; is
  recognized with number 0 ... 127. &ts; can be specified as a shorthand
  for <spec code="9"/>, a transparent space.
-->
<!ENTITY lt "&#38;#60;">
<!ENTITY gt "&#62;">
<!ENTITY amp "&#38;#38;">
<!ENTITY ts '<spec code="9"/>'>
<!ELEMENT cc608-test-stream (#PCDATA | aof | aon | bao | bas | bbo |
   bbs | bco |
   bcs | bgo | bgs | bmo | bms | bro | brs | bs | bt | bwo | bws |
   byo | bys | cr | der | edm | enm | eoc | fa | fau | fon | mr |
   pac | rcl | rdc | rtd | ru2 | ru3 | ru4 | to1 | to2 | to3 | tr |
   ext2 | ext3 | spec | cmd | pause | sync)*>
<!-- Control codes. -->
<!ELEMENT aof EMPTY><!-- Alarm off (0x1422). -->
<!ATTLIST aof ch CDATA #IMPLIED>
<!ELEMENT aon EMPTY><!-- Alarm on (0x1423). -->
<!ATTLIST aon ch CDATA #IMPLIED>
<!ELEMENT bao EMPTY><!-- Background black opaque (0x102E). -->
<!ATTLIST bao ch CDATA #IMPLIED>
<!ELEMENT bas EMPTY><!-- Background black semi-transparent (0x102F). -->
<!ATTLIST bas ch CDATA #IMPLIED>
<!ELEMENT bbo EMPTY><!-- Background blue opaque (0x1024). -->
<!ATTLIST bbo ch CDATA #IMPLIED>
<!ELEMENT bbs EMPTY><!-- Background blue semi-transparent (0x1025). -->
<!ATTLIST bbs ch CDATA #IMPLIED>
<!ELEMENT bco EMPTY><!-- Background cyan opaque (0x1026). -->
<!ATTLIST bco ch CDATA #IMPLIED>
<!ELEMENT bcs EMPTY><!-- Background cyan semi-transparent (0x1027). -->
<!ATTLIST bcs ch CDATA #IMPLIED>
<!ELEMENT bgo EMPTY><!-- Background green opaque (0x1022). -->
<!ATTLIST bgo ch CDATA #IMPLIED>
<!ELEMENT bgs EMPTY><!-- Background green semi-transparent (0x1023). -->
<!ATTLIST bgs ch CDATA #IMPLIED>
<!ELEMENT bmo EMPTY><!-- Background magenta opaque (0x102C). -->
<!ATTLIST bmo ch CDATA #IMPLIED>
<!ELEMENT bms EMPTY><!-- Background magenta semi-transparent (0x102D). -->
<!ATTLIST bms ch CDATA #IMPLIED>
<!ELEMENT bro EMPTY><!-- Background red opaque (0x1028). -->
<!ATTLIST bro ch CDATA #IMPLIED>
<!ELEMENT brs EMPTY><!-- Background red semi-transparent (0x1029). -->
<!ATTLIST brs ch CDATA #IMPLIED>
<!ELEMENT bs  EMPTY><!-- Backspace (0x1421). -->
<!ATTLIST bs  ch CDATA #IMPLIED>
<!ELEMENT bt  EMPTY><!-- Background transparent (0x172D). -->
<!ATTLIST bt  ch CDATA #IMPLIED>
<!ELEMENT bwo EMPTY><!-- Background white opaque (0x1020). -->
<!ATTLIST bwo ch CDATA #IMPLIED>
<!ELEMENT bws EMPTY><!-- Background white semi-transparent (0x1021). -->
<!ATTLIST bws ch CDATA #IMPLIED>
<!ELEMENT byo EMPTY><!-- Background yellow opaque (0x102A). -->
<!ATTLIST byo ch CDATA #IMPLIED>
<!ELEMENT bys EMPTY><!-- Background yellow semi-transparent (0x102B). -->
<!ATTLIST bys ch CDATA #IMPLIED>
<!ELEMENT cr  EMPTY><!-- Carriage return (0x142D). -->
<!ATTLIST cr  ch CDATA #IMPLIED>
<!ELEMENT der EMPTY><!-- Delete to end of row (0x1424). -->
<!ATTLIST der ch CDATA #IMPLIED>
<!ELEMENT edm EMPTY><!-- Erase displayed memory (0x142C). -->
<!ATTLIST edm ch CDATA #IMPLIED>
<!ELEMENT enm EMPTY><!-- Erase non-displayed memory (0x142E). -->
<!ATTLIST enm ch CDATA #IMPLIED>
<!ELEMENT eoc EMPTY><!-- End of caption (0x142F). -->
<!ATTLIST eoc ch CDATA #IMPLIED>
<!ELEMENT fa  EMPTY><!-- Foreground black (0x172E). -->
<!ATTLIST fa  ch CDATA #IMPLIED>
<!ELEMENT fau EMPTY><!-- Foreground black underlined (0x172F). -->
<!ATTLIST fau ch CDATA #IMPLIED>
<!ELEMENT fon EMPTY><!-- Flash on (0x1428). -->
<!ATTLIST fon ch CDATA #IMPLIED>
<!ELEMENT mr  EMPTY><!-- Midrow text color change (0x1120). -->
<!ATTLIST mr
  color CDATA #IMPLIED
  u CDATA #IMPLIED
  ch CDATA #IMPLIED>
<!-- Foreground color: 0 ... 7 (white, green, blue, cyan, red, yellow,
  magenta, white italic). If the color attribute is missing color 0
  will be encoded.

  Underlined text u: 0 ... 1. Default 0. -->
<!ELEMENT pac EMPTY><!-- Preamble Address Code (0x1n4n ... 0x1n7n). -->
<!ATTLIST pac
  row CDATA #IMPLIED
  column CDATA #IMPLIED
  color CDATA #IMPLIED
  u CDATA #IMPLIED
  ch CDATA #IMPLIED>
<!-- Move the cursor to row 1 ... 15. If the row attribute is missing
  row 15 will be encoded. Note: The row numbers follow the numbering
  scheme of 47 CFR 15.119. Row 1 is the topmost row, there is no zeroth
  row.

  Move the cursor to column 1 ... 32. A PAC does not transmit the
  lowest two bits of the column number, so it actually moves the cursor
  to column 1, 5, 9, 13 etc. It must be combined with a Tab Offset code
  to address all columns. Column 0 is not addressable but as described
  in 47 CFR 15.119 the caption decoder may add an opaque space to the
  left and right of text for legibility.

  Foreground color: 0 ... 7 (white, green, blue, cyan, red, yellow,
  magenta, white italic). A PAC can carry a column or color attribute
  but not both. If neither attribute is given, color 0 will be encoded.

  Underlined text u: 0 ... 1. Default 0. -->
<!ELEMENT rcl EMPTY><!-- Resume caption loading (0x1420). -->
<!ATTLIST rcl ch CDATA #IMPLIED>
<!ELEMENT rdc EMPTY><!-- Resume direct caption (0x1429). -->
<!ATTLIST rdc ch CDATA #IMPLIED>
<!ELEMENT rtd EMPTY><!-- Resume text display (0x142B). -->
<!ATTLIST rtd ch CDATA #IMPLIED>
<!ELEMENT ru2 EMPTY><!-- Roll up with two rows (0x1425). -->
<!ATTLIST ru2 ch CDATA #IMPLIED>
<!ELEMENT ru3 EMPTY><!-- Roll up with three rows (0x1426). -->
<!ATTLIST ru3 ch CDATA #IMPLIED>
<!ELEMENT ru4 EMPTY><!-- Roll up with four rows (0x1427). -->
<!ATTLIST ru4 ch CDATA #IMPLIED>
<!ELEMENT to1 EMPTY><!-- Tab offset one (0x1721). -->
<!ATTLIST to1 ch CDATA #IMPLIED>
<!ELEMENT to2 EMPTY><!-- Tab offset two (0x1722). -->
<!ATTLIST to2 ch CDATA #IMPLIED>
<!ELEMENT to3 EMPTY><!-- Tab offset three (0x1723). -->
<!ATTLIST to3 ch CDATA #IMPLIED>
<!ELEMENT tr  EMPTY><!-- Text restart (0x142A). -->
<!ATTLIST tr  ch CDATA #IMPLIED>
  <!-- There are four caption and four text channels. The ch attribute
    selects the channel number to be encoded in the command: 1 ... 4.
    If the ch attribute is missing the most recently specified channel
    number will be encoded, or channel 1 at the beginning of the test
    stream.

    Text commands switch to a text channel, caption commands to a
    caption channel. Channels 1 and 2 are always transmitted on the
    first field, 3 and 4 on the second field. This allows decoders to
    detect accidental field swapping. However only commands with the
    code 0x14nn transmit the field bit. Characters belong to the
    channel with the most recently transmitted number. -->
<!ELEMENT ext2 EMPTY>
  <!-- Extended character set character (0x12nn). -->
<!ATTLIST ext2
  code CDATA #IMPLIED
  ch CDATA #IMPLIED>
  <!-- Character code: 32 ... 63. Default 32. -->
<!ELEMENT ext3 EMPTY>
  <!-- Extended character set character (0x13nn). -->
<!ATTLIST ext3
  code CDATA #IMPLIED
  ch CDATA #IMPLIED>
  <!-- Character code: 32 ... 63. Default 32. -->
<!ELEMENT spec EMPTY>
  <!-- Special character set character (0x113n). -->
<!ATTLIST spec
  code CDATA #IMPLIED
  ch CDATA #IMPLIED>
  <!-- Character code: 0 ... 15. Default: 0. -->
<!-- Libzvbi stream control elements. -->
<!ELEMENT cmd EMPTY>
  <!-- Insert an arbitrary command, including parity bits. This
    element is intended to insert erraneous data. -->
<!ATTLIST cmd
  code CDATA #IMPLIED>
  <!-- (first byte 0 ... 255) * 256 + (second byte 0 ... 255). Default
    0. Hex syntax 0xNNNN is supported. -->
<!ELEMENT pause EMPTY>
  <!-- Insert pairs of zero bytes (0x8080). -->
<!ATTLIST pause frames CDATA #IMPLIED>
  <!-- How many pairs to insert: 1 ... INT_MAX. Default: 60
    (about two seconds). -->
<!ELEMENT sync EMPTY>
  <!-- Synchronize streams. Pauses caption on F1 or F2 until
    the same number of bytes have been transmitted on
    both fields. -->

<!--
Local Variables:
mode: sgml
indent-tabs-mode: nil
coding: utf-8
End:
-->

=== jwilk-mirrors/zvbi/test/cc608-roll-up.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cc608-test-stream SYSTEM "cc608-test-stream.dtd">
<!--
  Libzvbi EIA 608-B Closed Caption test stream: Roll-Up caption

  Copyright (C) 2008 Michael H. Schimek

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
  MA 02110-1301, USA.

  If this file helped you improve another caption implementation an
  acknowledgement would be appreciated.
-->

<cc608-test-stream>

<edm/><ru4 ch="1"/><pac row="15" column="1"/>

Libzvbi EIA 608-B Closed Caption<cr/>
test stream: Roll-Up caption.<pause frames="120"/><cr/>

This is Roll-Up caption on<cr/>
channel CC1. You can see four<cr/>
rows of text at the bottom of<cr/>
the screen.<pause frames="120"/>
 When we add a new<cr/>
row, the top row disappears<cr/>
and the remaining rows roll<cr/>
up.<pause frames="120"/><cr/>

<!-- 47 CFR 15.119 (d)(1): "In the Caption Mode, text can appear on up
  to 4 rows simultaneously anywhere on the screen within the defined
  display area. In addition, a solid space equal to one column width
  may be placed before the first character and after the last
  character of each row to enhance legibility. The caption area will
  be transparent anywhere that either: (i) No standard space character
  or other character has been addressed and no accompanying solid
  space is needed; or, (ii) An accompanying solid space is used and a
  transparent space special character has been addressed which does
  not immediately precede or follow a displayed character."

  47 CFR 15.119 (f)(1)(viii): "If a solid space is used for
  legibility, it should appear when the first displayable character
  (not a transparent space) or Mid-Row Code is received on a row, not
  when the Preamble Address Code, if any, is given. A row on which
  there are no displayable characters or Mid-Row Codes will not
  display a solid space, even when rolled up between two rows which do
  display a solid space." -->

These rows do not start or<cr/>
end with a space but the<cr/>
decoder may add one to<cr/>
enhance legibility.<pause frames="240"/><cr/>

 This row starts with a space.<cr/>
This row ends with a space. <cr/>
The decoder should not add<cr/>
another space.<pause frames="240"/><cr/>

The video picture is visible<cr/>
where no character or standard<cr/>
space &gt; &lt; is displayed.<cr/>
<pause frames="240"/><cr/>

The row below is empty.<cr/><cr/>
<cr/>
Throughout the row above the<cr/>
video picture is visible.<pause frames="240"/><cr/>

<!-- Transparent space is not a displayable character (47 CFR 15.119
  (n)(13)). -->
The row below is empty too.<cr/>
&ts;<cr/>
Actually one transparent space<cr/>
character was transmitted.<pause frames="240"/><cr/>

<!-- MR is a spacing attribute. A standard space is a displayable
  character (47 CFR 15.119 (n)(6) et al) but it's pointless to
  pad a space. -->
This row contains one space:<cr/>
<mr color="0"/><cr/>
The decoder should display<cr/>
one space.<pause frames="240"/><cr/>

  This row starts w. 2 spaces.<cr/>
This row ends with 2 spaces.  <cr/>
The decoder should display two<cr/>
spaces in both rows.<pause frames="240"/><cr/>

This &gt;&ts;&lt; is a transparent<cr/>
space, a space character with<cr/>
transparent background, where<cr/>
the video picture is visible.<pause frames="240"/><cr/>

&ts;This row starts with a<cr/>
transparent space. The decoder<cr/>
may replace it by one opaque<cr/>
space for legibility.<pause frames="240"/><cr/>

A transparent space follows<cr/>
the comma in this row,&ts;<cr/>
the decoder may replace it<cr/>
by one opaque space.<pause frames="240"/><cr/>

<!-- 47 CFR 15.119 (i)(1): "Each control code consists of a pair of
  bytes which are always transmitted together in a single field of
  line 21 and which are normally transmitted twice in succession to
  help insure correct reception of the control instructions." -->

Control codes (like Special<cr/>
Character Transparent Space)<cr/>
may repeat once to ensure<cr/>
correct reception.<pause frames="240"/><cr/>

&ts;&ts;&ts;This row starts with two<cr/>
transparent spaces, but three<cr/>
were transmitted.<pause frames="240"/><cr/>

&ts;&ts;&ts;&ts;This row also starts with two<cr/>
transparent spaces, but four<cr/>
were transmitted.<pause frames="240"/><cr/>

&ts;&ts;&ts;&ts;This row starts with two<cr/>
transp. spaces. The decoder<cr/>
may replace the second one<cr/>
by an opaque space.<pause frames="240"/><cr/><cr/>

<!-- 47 CFR 15.119 (e)(1)(i): "The first type of addressing code is
  the Preamble Address Code (PAC). It assigns a row number and one of
  eight indent figures. Each successive indent moves the cursor four
  columns to the right (starting from the left margin). Thus, an
  indent of 0 places the cursor at Column 1, an indent of 4 sets it at
  Column 5, etc. The PAC indent is non-destructive to displayable
  characters. It will not affect the display to the left of the new
  cursor position on the indicated row. Note that Preamble Address
  Codes also set initial attributes for the displayable characters
  which follow. See paragraph (h) of this section and the Preamble
  Address Code table."

  47 CFR 15.119 (e)(1)(ii) The second type of addressing code is the
  Tab Offset, which is one of three Miscellaneous Control Codes. Tab
  Offset will move the cursor one, two, or three columns to the
  right. The character cells skipped over will be unaffected;
  displayable characters in these cells, if any, will remain intact
  while empty cells will remain empty, in the same manner that a PAC
  indent is non-destructive." -->

<to1/>This row is indented by<cr/>
one column using a TO1 code.<pause frames="240"/><cr/>

<to2/>This row is indented by<cr/>
two columns using a TO2 code.<pause frames="240"/><cr/>

<to3/>This row is indented by<cr/>
three columns using a TO3<cr/>
code.<pause frames="240"/><cr/>

<to2/><to2/><to2/><to2/>
This row is indented by<cr/>
four columns, using two TO2<cr/>
codes, four were transmitted.<pause frames="240"/><cr/>

<pac column="5"/>
This row is indented by<cr/>
four columns using a PAC<cr/>
code.<pause frames="240"/><cr/>

&ts;&ts;&ts;&ts;&ts;&ts;&ts;&ts;
&lt; four transp. spaces.<cr/>
<to1/><to3/>
&lt; four transp. spaces.<cr/>
<pac column="5"/>
&lt; four transp. spaces.<cr/>
3 rows above are identical.<pause frames="120"/><cr/>

This row ends with two&ts;&ts;&ts;&ts;<cr/>
transp. spaces. The decoder<cr/>
may replace the first one<cr/>
by an opaque space.<pause frames="240"/><cr/>

<!-- 678901234567890123456789012 -->
Transparent spaces &gt;
&ts;&ts;&ts;&ts;&ts;&ts;&ts;&ts;<cr/>
Transparent spaces &gt;<to3/><to1/><cr/>
Transparent spaces &gt;<pac column="21"/><cr/>
3 rows above are identical.<pause frames="120"/><cr/>

This row &gt;&ts;&ts;&ts;&ts;&ts;&ts;&lt; contains three<cr/>
transp. spaces. The decoder<cr/>
may replace the first and<cr/>
third one by opaque spaces.<pause frames="240"/><cr/>

Three   &gt;&ts;&ts;&ts;&ts;&ts;&ts;&lt; transp. spaces.<cr/>
Three   &gt;<to3/>&lt; transp. spaces.<cr/>
Three   &gt;<pac column="13"/>&lt; transp. spaces.<cr/>
3 rows above are identical.<pause frames="120"/><cr/><cr/>

<!-- 47 CFR 15.119 (d):"This display area will be further divided into
  15 character rows of equal height and 32 columns of equal width, to
  provide accurate placement of text on the screen." -->
There are 32 columns:<cr/>
12345678901234567890123456789012<cr/>
The row above begins with<cr/>
"1234" and ends with "9012".<pause frames="240"/><cr/>

We move the cursor to each<cr/>
column using one PAC and one<cr/>
TOx code:<pause frames="120"/><cr/>
<!-- Note PACs do not carry the two last significant bits of
  the column. -->
12345678901234567890123456789012<cr/>
<pac column="1"/>1<cr/>
<pac column="1"/><to1/>2<cr/>
<pac column="1"/><to2/>3<pause frames="120"/><cr/>
12345678901234567890123456789012<cr/>
<pac column="1"/><to3/>4<cr/>
<pac column="5"/>5<cr/>
<pac column="5"/><to1/>6<pause frames="120"/><cr/>
12345678901234567890123456789012<cr/>
<pac column="5"/><to2/>7<cr/>
<pac column="5"/><to3/>8<cr/>
<pac column="9"/>9<pause frames="120"/><cr/>
12345678901234567890123456789012<cr/>
<pac column="9"/><to1/>10<cr/>
<pac column="9"/><to2/>11<cr/>
<pac column="9"/><to3/>12<pause frames="120"/><cr/>
12345678901234567890123456789012<cr/>
<pac column="13"/>13<cr/>
<pac column="13"/><to1/>14<cr/>
<pac column="13"/><to2/>15<pause frames="120"/><cr/>
12345678901234567890123456789012<cr/>
<pac column="13"/><to3/>16<cr/>
<pac column="17"/>17<cr/>
<pac column="17"/><to1/>18<pause frames="120"/><cr/>
12345678901234567890123456789012<cr/>
<pac column="17"/><to2/>19<cr/>
<pac column="17"/><to3/>20<cr/>
<pac column="21"/>21<pause frames="120"/><cr/>
12345678901234567890123456789012<cr/>
<pac column="21"/><to1/>22<cr/>
<pac column="21"/><to2/>23<cr/>
<pac column="21"/><to3/>24<pause frames="120"/><cr/>
12345678901234567890123456789012<cr/>
<pac column="25"/>25<cr/>
<pac column="25"/><to1/>26<cr/>
<pac column="25"/><to2/>27<pause frames="120"/><cr/>
12345678901234567890123456789012<cr/>
<pac column="25"/><to3/>28<cr/>
<pac column="29"/>29<cr/>
<pac column="29"/><to1/>30<pause frames="120"/><cr/>
12345678901234567890123456789012<cr/>
<pac column="29"/><to2/>31<pause frames="120"/><cr/>
12345678901234567890123456789012<cr/>
<pac column="29"/><to3/>X<cr/>
The row above contains only<cr/>
one "X" in column 32.<pause frames="240"/><cr/><cr/>
